name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - run: pip install poetry
      - run: poetry install --with dev
      - run: poetry run black . --check        # Linting (optional)
      - run: poetry run flake8 timemesh        # Code style (optional)
      - run: poetry run pytest -v --cov=timemesh --cov-fail-under=80
      - name: Upload coverage
        uses: codecov/codecov-action@v3
